language: node_js
node_js:
  - 0.10

notifications:
  email:
    on_failure: always # [always|never|change] default: always

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"